### ISSUE TITLE
Can we get the most current version?

### ISSUE THREAD

**Issue by kupietools** [wrandelshofer/VirtualCube#4]
Clearly the script version live on the demo site is newer than what's here, it has features that aren't in this version, such as additional cubes, and the controls under the cubes in this screenshot. The live site says the code is under MIT license, is there a chance you could post it? Thanks.

<img width="931" alt="Screen Shot 2024-10-09 at 3 46 41 PM" src="https://github.com/user-attachments/assets/eeab7770-f1fe-4a57-8edc-80dbd7fcb825">

**Comment by wrandelshofer** [comment]
Oops. I have published it now. The version number is 1.0.11.
